/*
 * AUTH
 */
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const LOG_OUT = 'LOG_OUT'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const AUTH_CHANGE_VALUE = 'AUTH_CHANGE_VALUE'

/*
 * COURSE
 */
export const FETCH_ALL_COURSES = 'FETCH_ALL_COURSES'
export const FETCH_COURSE = 'FETCH_COURSE'
export const COURSE_CHANGE_VALUE = 'COURSE_CHANGE_VALUE'
