/*
 * AUTH
 */
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const LOG_OUT = 'LOG_OUT'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const AUTH_CHANGE_VALUE = 'AUTH_CHANGE_VALUE'

/*
 * USER
 */
export const FETCH_USER = 'FETCH_USER'
export const USER_CHANGE_VALUE = 'USER_CHANGE_VALUE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_NEXT_PAGE = 'USER_NEXT_PAGE'

/*
 * COURSE
 */
export const FETCH_ALL_COURSES = 'FETCH_ALL_COURSES'
export const FETCH_COURSE = 'FETCH_COURSE'
export const COURSE_CHANGE_VALUE = 'COURSE_CHANGE_VALUE'
export const SEARCH_COURSE = 'SEARCH_COURSE'

export const UPDATE_COURSE = 'UPDATE_COURSE'
export const ADD_NEW_SECTION = 'ADD_NEW_SECTION'
export const EDIT_SECTION = 'EDIT_SECTION'
export const REMOVE_SECTION = 'REMOVE_SECTION'

export const CLEAR_COURSE_FILTER = 'CLEAR_COURSE_FILTER'
export const CHANGE_COURSE_PHOTO = 'CHANGE_COURSE_PHOTO'
export const MY_COURSE = 'MY_COURSE'

/*
 * CART
 */
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_THE_CART = 'REMOVE_FROM_THE_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const PAY_CART = 'PAY_CART'

